RESET master;
BEGIN; COMMIT;

CHANGE MASTER TO MASTER_HOST = 'master', MASTER_USER = 'repl', MASTER_PASSWORD = 'repl' , MASTER_AUTO_POSITION = 1 FOR CHANNEL 'master';
START SLAVE  FOR CHANNEL  'master';